### ISSUE TITLE
display tag does not render associations

### ISSUE THREAD

**Issue by houbie** [grails3-plugins/fields#1]
The `FormFieldsTagLib` still contains a TODO for this.
The check `if(prop.isAssociation())` must be moved to `renderForDisplay`, otherwise there is no way to overwrite the default template for the association property. Probably the check can just be deleted to have something useful displayed.

**Comment by bodiam** [comment]
Same here. I have a class called Person, with an Address inside, and it would be nice if the toString was called in the show.gsp view, or all the fields are rendered just like when editing.

**Comment by graemerocher** [comment]
So this was fixed by https://github.com/grails3-plugins/fields/commit/0fb3a577cfadcad5d3a26db8babc649ba70dfcf4 

Thanks @houbie
