### ISSUE TITLE
NPE Coming Out Of The Table Tag

### ISSUE THREAD

**Issue by jeffbrown** [grails3-plugins/fields#12]
If an entity has a null reference to some association, the `table` tag will NPE when rendering that instance.

A simple way to recreate the problem is to define an entity with a nullable relationship:

    package demo

    class Person {
        String name
        Address homeAddress
        static constraints = {
            homeAddress nullable: true
        }
    }

Generate default scaffolding for the `Person` class.

Persist an instance of `Person` without initializing `homeAddress`.

    class BootStrap {

        def init = { servletContext ->
            new demo.Person(name: 'Herman').save()
        }
        def destroy = {
        }
    }

Visit the default scaffolded list page for `Person`.

The problem is likely at https://github.com/grails3-plugins/fields/blob/c296248fcc5c78557743bfe286956a3ab36aa008/grails-app/taglib/grails/plugin/formfields/FormFieldsTagLib.groovy#L576.

**Comment by graemerocher** [comment]
Doesn't this duplicate #10 ?

**Comment by jeffbrown** [comment]
Yes, I think it does.  I looked and somehow didn't see that.  That is my mistake.
