### ISSUE TITLE
Features from the latest version of the Grails 2 version of the fields plugin (1.5) missing from the Grails 3 version

### ISSUE THREAD

**Issue by scrain** [grails3-plugins/fields#13]
The Grails 3 version of this plugin was forked from the 1.4 version of the Grails 2 Fields plugin in late 2014.  Since then version 1.5 was released with some new features, namely the new ` _displayWrapper.gsp` template.  More details on that feature are [here](http://grails-fields-plugin.github.io/grails-fields/guide/customizingFieldRendering.html) in the documentation.

**Comment by jeffbrown** [comment]
@domurtag Do you have any availability and interest to help catch the Grails 3 plugin up with the features that have been added to the Grails 2 plugin?

Please let me know.  I appreciate your feedback.

**Comment by graemerocher** [comment]
The latest changes have been merged into 2.1.0-SNAPSHOT

**Comment by donalmurtagh** [comment]
is there any reason why we shouldn't go ahead and release this?

**Comment by graemerocher** [comment]
@donalmurtagh Just testing purposes, would be nice to merge the 2 forks and have one.... I'm not bothered where the preferred home is.

it is already available in snapshot form, but needs move thorough testing...

**Comment by donalmurtagh** [comment]
I agree that we should have a single fork and I think it should be https://github.com/grails-plugins/grails-fields

@graemerocher could you submit a PR to merge the latest in this fork back to https://github.com/grails-plugins/grails-fields

**Comment by graemerocher** [comment]
@donalmurtagh It would be better to maintain a `Grails2` branch and keep master as Grails 3, this is in keeping with other plugins
