### ISSUE TITLE
Grails 3.0.1 Missing documentation on <f:table>

### ISSUE THREAD

**Issue by bodiam** [grails3-plugins/fields#6]
It's missing in the tags, but I'd like to know it I could change the columns which are displayed, for example, and if parameters like 'except' are also supported here.

**Comment by houbie** [comment]
It is documented, but the documentation link points to an old 1.5 version

**Comment by graemerocher** [comment]
More up-to-date docs http://grails3-plugins.github.io/fields/snapshot/
